version: 2

project_name: lokex-cli

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: cli
    main: .
    binary: lokex-cli
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X github.com/bodrovis/lokalise-glossary-guard/cmd.version={{ .Version }}
        -X github.com/bodrovis/lokalise-glossary-guard/cmd.commit={{ .Commit }}
        -X github.com/bodrovis/lokalise-glossary-guard/cmd.date={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

  - id: wasm
    main: .
    binary: lokex-cli.wasm
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X github.com/bodrovis/lokex-cli/cmd.version={{ .Version }}
        -X github.com/bodrovis/lokex-cli/cmd.commit={{ .Commit }}
        -X github.com/bodrovis/lokex-cli/cmd.date={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - js
    goarch:
      - wasm

upx:
  - ids:
      - cli
    enabled: true
    compress: best
    lzma: true
    brute: false
    goos:
      - linux
      - windows

archives:
  - id: cli
    ids:
      - cli
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README*
      - LICENSE*
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: wasm
    ids:
      - wasm
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_wasm"
    files:
      - README*
      - LICENSE*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive

signs:
  - id: checksums
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    artifacts: checksum
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"

release:
  draft: false
  prerelease: auto
  mode: replace

changelog:
  disable: true