name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # v7.0.0
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    # v6.5.0
    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
      with:
        go-version-file: go.mod
        check-latest: false
        cache: false
        

    - name: Check Go modules
      run: |
        set -euo pipefail
        go mod tidy
        git diff --exit-code -- go.mod go.sum
        go mod verify

    - name: Run tests
      run: go test -count=1 -coverprofile=coverage.out ./... -v -shuffle=on

      # v2.3.0
    - uses: qltysh/qlty-action/coverage@08a0a862c159eae9b9003081da6663d96efef637
      with:
        token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: coverage.out
        strip-prefix: github.com/bodrovis/lokex-cli/